// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpMk4P2UUDDo66ESeb-3aaI0YsMRBD4o',
    appId: '1:395019409667:web:7aeb41abae5f12c88e3136',
    messagingSenderId: '395019409667',
    projectId: 'proyekdelivery',
    authDomain: 'proyekdelivery.firebaseapp.com',
    storageBucket: 'proyekdelivery.firebasestorage.app',
    measurementId: 'G-NTQWMTFXFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0x2b4-WUpq1VxDGTICDV-vq2gHg41do',
    appId: '1:395019409667:android:5a272e25caeee8198e3136',
    messagingSenderId: '395019409667',
    projectId: 'proyekdelivery',
    storageBucket: 'proyekdelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeeTZgrNUz4WiWuEzAo3p3ojoHBVRcx8Y',
    appId: '1:395019409667:ios:c64bac1bb0b1a4a28e3136',
    messagingSenderId: '395019409667',
    projectId: 'proyekdelivery',
    storageBucket: 'proyekdelivery.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeeTZgrNUz4WiWuEzAo3p3ojoHBVRcx8Y',
    appId: '1:395019409667:ios:c64bac1bb0b1a4a28e3136',
    messagingSenderId: '395019409667',
    projectId: 'proyekdelivery',
    storageBucket: 'proyekdelivery.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIpMk4P2UUDDo66ESeb-3aaI0YsMRBD4o',
    appId: '1:395019409667:web:393abd1f851dea388e3136',
    messagingSenderId: '395019409667',
    projectId: 'proyekdelivery',
    authDomain: 'proyekdelivery.firebaseapp.com',
    storageBucket: 'proyekdelivery.firebasestorage.app',
    measurementId: 'G-SJ7326J2QF',
  );
}
